
[language.haskell]
filetypes = ["haskell"]
roots = ["Setup.hs", "stack.yaml", "*.cabal"]
command = "haskell-language-server-wrapper-2.2.0.0"
args = ["--lsp"]

[language.c_cpp]
filetypes = ["c", "cpp", "objc", "objcpp", "cuda"]
roots = [".ccls", "compile_commands.json", "Makefile"]
command = "clangd"
